server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
#      defaultZone: http://eureka-server:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: false

spring:
  application:
    name: hello
  zipkin:
      base-url: http://localhost:9040

---
spring:
  profiles: 9002

server:
  port: 9002