server:
  port: 9020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: zuul

zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon
    feign:
      path: /feign/**
      serviceId: feign
