eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9011
spring:
  application:
    name: feign
  cloud:
      config:
        uri: http://localhost:9030/
        label: master
        profile: dev
feign:
  hystrix:
    enabled: true
