eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9011
spring:
  application:
    name: feign
  zipkin:
    base-url: http://localhost:9040
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false