server:
  port: 9030

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/simplexity-ckcclc/configserver
          username:
          password:
          search-paths: config
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zk-nodes: 127.0.0.1:2181

management.security.enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
